### ISSUE TITLE
Chrono Solidworks versions don't match Chronos API

### ISSUE THREAD

**Issue by hauptmech** [projectchrono/chrono-solidworks#2]
Using chronos 5.0 with [Download Chrono::SolidWorks v.4.0.1 add-in for SolidWorks 2014 and higher. Chrono 4.0 and 5.0 compatible.](http://www.projectchrono.org/assets/installers/ChronoEngine_SolidWorks_v4.02.exe) results in a `run_test.py` that fails because `SetMaxItersSolverSpeed` is not in the 5.0 API.

Is it possible to fix the git tag and re-issue an installer for chrono-solidworks that works with Chrono 5.0?

**Comment by rserban** [comment]
Please check out [http://projectchrono.org/download/](http://projectchrono.org/download/).
We provided a version of the add-in that should work with Chrono and PyChrono 5.0.
Let us know if you encounter any problems.
