### ISSUE TITLE
Link to ground leads to wrong exported code

### ISSUE THREAD

**Issue by dariomangoni** [projectchrono/chrono-solidworks#3]
In the CPP and Python exported code, when a link involves the "ground" body, the following line appears:
`motor_0_1.Initialize(body_23, SLDW_GROUND, ...`
instead of:
`motor_0_1.Initialize(body_23, body_0, ...`

**Comment by dariofusai93** [comment]
Fixed in commit 84020b83449f25d14228c690b7709f0ec69c7ea2
